# relations/interface.jl — the uniform three-verb contract for relations,
# the @relation declaration macro, and the adoption surface.
#
# A relation is an *identity among observables or exponents* — a generic,
# model-independent statement.  Each is DECLARED EXACTLY ONCE via
# [`@relation`](@ref); everything else (solving for any affine variable,
# checking, β-or-T normalization, registry membership, introspection) is
# derived mechanically.  No hand-written rearrangements, no per-relation
# boilerplate.
#
# Architecture:
#
#   public verbs   residual / check / solve      (β-or-T normalization, one place)
#   kernels        _residual (ONE per relation)  |  _solve (rare, non-affine only)
#   traits         variables(rel), domain(rel)
#   registry       all_relations / applicable_relations / relation_report / check_all

"""
    AbstractRelation

Abstract parent type for physics relations.  Concrete relations are
declared with [`@relation`](@ref) and implement the three verbs:

- [`residual`](@ref)`(rel; vars...)` — signed violation; `0` ⇔ satisfied.
- [`check`](@ref)`(rel; atol=0, vars...)` — `|residual| ≤ atol`.
- [`solve`](@ref)`(rel, Val(:x); vars...)` — the value of `x` implied by
  the remaining variables.

**Exact-arithmetic contract**: `residual` and `solve` must not promote
their inputs — `Rational` in ⇒ `Rational` out, so exactly-known values
(e.g. the 2D Ising exponents) satisfy their relations *exactly*
(`residual == 0//1`), not merely to floating-point tolerance.

Relations whose variables include an inverse temperature accept either
`β` or `T` (exactly one) at every public verb; the normalization happens
once, in the verb layer — kernels only ever see `β`.
"""
abstract type AbstractRelation end
export AbstractRelation

# the residual kernel generic function — one method per relation,
# generated by @relation.  Public code calls `residual`, never this.
function _residual end

# ─── Traits ─────────────────────────────────────────────────────────────

"""
    variables(rel::AbstractRelation) -> Tuple{Vararg{Symbol}}

The *required* variables of the relation (optional variables with
defaults, e.g. a site count `N = 1`, are not listed).  Filled in by
[`@relation`](@ref); used for applicability matching in
[`applicable_relations`](@ref) and by the β-or-T normalizer.
"""
function variables end
export variables

"""
    domain(rel::AbstractRelation) -> Symbol

The relation's family tag (`:scaling`, `:thermodynamic`,
`:fundamental`, `:topology`, …) — for filtering in the registry API,
and for disambiguating same-named variables across families (the
exponent `β` vs the inverse temperature `β`).
"""
function domain end
export domain

# ─── Registry ───────────────────────────────────────────────────────────

const _RELATION_REGISTRY = AbstractRelation[]

"""
    all_relations(; domain=nothing) -> Vector{AbstractRelation}

Every relation declared with [`@relation`](@ref) in this package,
optionally filtered by [`domain`](@ref).  The registry is what makes the
package *adoptable in one call*: a consumer never hand-lists relations
(see [`relation_report`](@ref)).
"""
function all_relations(; domain::Union{Nothing,Symbol}=nothing)
    domain === nothing && return copy(_RELATION_REGISTRY)
    return filter(r -> AbstractQAtlas.domain(r) === domain, _RELATION_REGISTRY)
end
export all_relations

# ─── β-or-T normalization (single point) ────────────────────────────────

# `solving` is the solve-target variable (or `nothing` for residual/
# check): when β itself is being solved for, the β-or-T demand is waived
# — the probes supply it.  (Physics overloads β: the same normalization
# serves the inverse temperature and steps aside for the exponent.)
function _normalize_kwargs(
    rel::AbstractRelation, kwargs::NamedTuple; solving::Union{Nothing,Symbol}=nothing
)
    :β in variables(rel) || return kwargs
    hasβ = haskey(kwargs, :β)
    hasT = haskey(kwargs, :T)
    if solving === :β
        (hasβ || hasT) && error("cannot pass β or T while solving for :β")
        return kwargs
    end
    hasβ && hasT && error("pass either β or T, not both")
    hasβ && return kwargs
    hasT || error("pass either β or T")
    rest = Base.structdiff(kwargs, NamedTuple{(:T,)})
    return merge(rest, (β=1 / kwargs.T,))
end

# ─── Public verbs ───────────────────────────────────────────────────────

"""
    residual(rel::AbstractRelation; vars...) -> Number

Signed violation of the relation at the given variable values; zero if
and only if the relation is satisfied.  Preserves the input number types
(see the exact-arithmetic contract on [`AbstractRelation`](@ref)).
"""
function residual(rel::AbstractRelation; kwargs...)
    return _residual(rel; _normalize_kwargs(rel, values(kwargs))...)
end
export residual

"""
    check(rel::AbstractRelation; atol=0, vars...) -> Bool

`abs(residual(rel; vars...)) ≤ atol`.  With the default `atol = 0` this
is an *exact* test — appropriate for `Rational` inputs; pass an explicit
`atol` for floating-point / error-bar data.
"""
check(rel::AbstractRelation; atol=0, kwargs...) = abs(residual(rel; kwargs...)) <= atol
export check

"""
    AbstractInequality <: AbstractRelation

A relation asserting an **inequality** rather than an equality.  Its
[`residual`](@ref) is the **slack in the `≥ 0` form**: the relation holds
iff `residual ≥ 0` (within tolerance), so [`check`](@ref) tests that
direction instead of `abs(residual) ≤ atol`.  [`solve`](@ref) still
returns the **saturation** value — where the slack vanishes, i.e. the
tight bound (e.g. `solve(Subadditivity(), Val(:S_AB))` gives the maximum
`S_A + S_B`).  Declared with [`@inequality`](@ref).
"""
abstract type AbstractInequality <: AbstractRelation end
export AbstractInequality

# an inequality holds when its slack is non-negative (float noise: ≥ −atol)
check(rel::AbstractInequality; atol=0, kwargs...) = residual(rel; kwargs...) >= -atol

"""
    slack(ineq::AbstractInequality; vars...) -> Number

The non-negativity margin of an inequality — its [`residual`](@ref): how
far from saturation, negative iff the inequality is violated.
"""
slack(rel::AbstractInequality; kwargs...) = residual(rel; kwargs...)
export slack

# whether a relation passes on the given (already-normalized) data — the
# polymorphic per-kind test used by `relation_report`/`check_all`, so an
# `AbstractInequality` is judged by its `≥ 0` direction, not `abs ≤ atol`.
_passes(rel::AbstractRelation, r, atol) = abs(r) <= atol
_passes(rel::AbstractInequality, r, atol) = r >= -atol

"""
    solve(rel::AbstractRelation, ::Val{x}; vars...) -> Number

The value of variable `x` implied by the relation and the remaining
variables, e.g. `solve(Widom(), Val(:γ); β=1//8, δ=15//1) == 7//4`.

No per-variable rearrangements are hand-written: for any variable the
relation is *affine* in (true of almost every identity here), the answer
follows exactly from three kernel evaluations — see the generic
`_solve`.  A relation that is non-affine in some variable provides a
specialized `_solve` for it (e.g. `FreeEnergyFromZ` for `Z`); attempting
a generic solve for a non-affine variable throws instead of silently
returning a wrong value.  Preserves input number types.
"""
function solve(rel::AbstractRelation, v::Val{X}; kwargs...) where {X}
    return _solve(rel, v; _normalize_kwargs(rel, values(kwargs); solving=X)...)
end
export solve

# Generic solve: for a residual r(x) affine in x, r(x) = r₀ + (r₁ − r₀)x
# exactly, so the root is x* = −r₀/(r₁ − r₀).  Three probes (x = 0, 1, 2)
# both solve and VERIFY affinity: the parabola test r₂ − 2r₁ + r₀ must
# vanish — exactly for exact inputs (Integer/Rational), to a relative
# 1e-8 for inexact ones (float OR complex-float — `abs` handles both).
# Integer probes promote correctly, so Rational data stays Rational.
function _solve(rel::AbstractRelation, ::Val{X}; kwargs...) where {X}
    kw = values(kwargs)
    at(v) = _residual(rel; merge(kw, NamedTuple{(X,)}((v,)))...)
    r0, r1, r2 = at(0), at(1), at(2)
    curv = r2 - 2r1 + r0
    isaffine = if curv isa Union{Integer,Rational}
        iszero(curv)                              # exact types: exact test
    elseif !all(isfinite, (r0, r1, r2))
        # A non-finite probe (a 1/x term evaluated at an integer probe, x=0)
        # means the residual blows up — not safely affine-solvable here.
        # Guard before `scale` goes to Inf and silently defeats the test.
        false
    else
        scale = max(abs(r0), abs(r1), abs(r2))    # float / complex: relative tol
        abs(curv) <= 1e-8 * max(scale, oneunit(scale))
    end
    isaffine || error(
        "solve: $(typeof(rel)) is not affine in :$X (or blows up at an integer " *
        "probe) — define a specialized _solve(::$(typeof(rel)), ::Val{:$X}; ...) " *
        "for this variable",
    )
    b = r1 - r0
    iszero(b) && error("solve: $(typeof(rel)) does not depend on :$X")
    return -r0 / b
end

# ─── The declaration macros ─────────────────────────────────────────────

# Shared code generation for `@relation` (equality) and `@inequality`
# (≥ 0 slack).  `super` is the supertype the generated struct subtypes,
# `what` names the macro for error messages.
function _build_relation(dom, defn, super::Symbol, what::String)
    Meta.isexpr(defn, :(=), 2) || error("$what expects `Name(vars...) = expr`, got $defn")
    call, body = defn.args
    Meta.isexpr(call, :call) || error("$what: left side must be a call, got $call")
    name = call.args[1]
    name isa Symbol || error("$what: relation name must be a Symbol")
    required = Symbol[]
    kwargsig = Any[]
    for p in call.args[2:end]
        if p isa Symbol
            push!(required, p)
            push!(kwargsig, esc(p))
        elseif Meta.isexpr(p, :(=), 2) || Meta.isexpr(p, :kw, 2)
            push!(kwargsig, Expr(:kw, esc(p.args[1]), esc(p.args[2])))
        else
            error("$what: cannot parse parameter $p")
        end
    end
    # kernels slurp extra keywords so relation_report can splat full data
    push!(kwargsig, Expr(:..., esc(gensym("extra"))))
    ename = esc(name)
    # NB: every generated method is module-QUALIFIED — short-form
    # definitions inside a macro quote are otherwise hygienized into
    # gensym locals, and qualification also makes the macros usable from
    # downstream modules (methods land on OUR generics, on THEIR type —
    # the intended extension pattern, not piracy).
    kernel_sig = Expr(
        :call, :(AbstractQAtlas._residual), Expr(:parameters, kwargsig...), :(::$ename)
    )
    kernel = Expr(:function, kernel_sig, esc(body))
    reqtuple = Expr(:tuple, (QuoteNode(s) for s in required)...)
    domval = QuoteNode(dom isa QuoteNode ? dom.value : dom)
    supertype = :(AbstractQAtlas.$super)
    return quote
        Core.@__doc__ struct $ename <: $supertype end
        $kernel
        AbstractQAtlas.variables(::$ename) = $reqtuple
        AbstractQAtlas.domain(::$ename) = $domval
        push!(AbstractQAtlas._RELATION_REGISTRY, $ename())
        $(Expr(:export, name))
        $ename
    end
end

"""
    @relation :domain Name(x, y, z, opt=default) = expr

Declare a relation ONCE.  Expands to the complete implementation:

- `struct Name <: AbstractRelation end` (docstring-attachable),
- the residual kernel `_residual(::Name; x, y, z, opt=default) = expr`
  (kernels tolerate extra keywords, so a whole data set can be splatted
  through [`relation_report`](@ref)),
- `variables(::Name) = (:x, :y, :z)` — required variables only,
- `domain(::Name) = :domain`,
- registry insertion and `export Name`.

`residual`/`check` work immediately; `solve` works for every variable
the expression is affine in.  Note for downstream packages declaring
their own relations: the struct and methods precompile fine, but the
registry insertion is a load-time side effect — re-register from your
module `__init__` if you need registry visibility across sessions.

```julia
@relation :scaling Rushbrooke(α, β, γ) = α + 2β + γ - 2
```
"""
macro relation(dom, defn)
    return _build_relation(dom, defn, :AbstractRelation, "@relation")
end
export var"@relation"

"""
    @inequality :domain Name(x, y, z, opt=default) = expr

Declare an INEQUALITY relation, `expr ≥ 0`.  Identical to
[`@relation`](@ref) but the generated struct subtypes
[`AbstractInequality`](@ref): `residual` returns the slack `expr`,
`check` tests `expr ≥ −atol`, and `solve` returns the saturation value.

```julia
@inequality :entanglement Subadditivity(S_A, S_B, S_AB) = S_A + S_B - S_AB
```
"""
macro inequality(dom, defn)
    return _build_relation(dom, defn, :AbstractInequality, "@inequality")
end
export var"@inequality"

# ─── Adoption surface: one-call verification over a data set ────────────

function _normalize_data(data::NamedTuple)
    return haskey(data, :T) && !haskey(data, :β) ? merge(data, (β=1 / data.T,)) : data
end

"""
    applicable_relations(data::NamedTuple; domain=nothing) -> Vector{AbstractRelation}

The registered relations whose required [`variables`](@ref) are all
present in `data` (after β-or-T normalization), optionally filtered by
[`domain`](@ref).  This is how a consumer package discovers what can be
checked against its observables — no hand-listing.

Pass `domain` when mixing families in one data set: variable names are
matched literally, and physics overloads symbols across families (the
critical exponent `β` vs the inverse temperature `β`).
"""
function applicable_relations(data::NamedTuple; domain::Union{Nothing,Symbol}=nothing)
    d = _normalize_data(data)
    ks = keys(d)
    return filter(r -> all(v -> v in ks, variables(r)), all_relations(; domain=domain))
end
export applicable_relations

"""
    relation_report(data::NamedTuple; atol=0, domain=nothing)
        -> Vector{@NamedTuple{relation::AbstractRelation, residual::Number, pass::Bool}}

Evaluate every applicable relation against `data` and report per-relation
residuals.  The one-call integration point for downstream packages:

```julia
# gate an exponent table (an atlas registry, MC-extracted exponents, …):
relation_report((; α=0//1, β=1//8, γ=7//4, δ=15//1, ν=1//1, η=1//4, d=2))

# cross-check measured thermodynamics against every applicable identity:
relation_report((; C=c, var_E=v, β=β, N=N); atol=tol)
```
"""
function relation_report(data::NamedTuple; atol=0, domain::Union{Nothing,Symbol}=nothing)
    d = _normalize_data(data)
    out = @NamedTuple{relation::AbstractRelation, residual::Number, pass::Bool}[]
    for rel in applicable_relations(d; domain=domain)
        r = _residual(rel; d...)
        push!(out, (relation=rel, residual=r, pass=_passes(rel, r, atol)))
    end
    return out
end
export relation_report

"""
    check_all(data::NamedTuple; atol=0, domain=nothing) -> Bool

`true` iff every applicable relation passes on `data` — and at least one
relation applies: an empty match is `false`, never a silent green.
"""
function check_all(data::NamedTuple; atol=0, domain::Union{Nothing,Symbol}=nothing)
    report = relation_report(data; atol=atol, domain=domain)
    return !isempty(report) && all(row -> row.pass, report)
end
export check_all
