# relations/interface.jl — the uniform three-verb contract for relations,
# the @relation declaration macro, and the adoption surface.
#
# A relation is an *identity among observables or exponents* — a generic,
# model-independent statement.  Each is DECLARED EXACTLY ONCE via
# [`@relation`](@ref); everything else (solving for any affine variable,
# checking, β-or-T normalization, registry membership, introspection) is
# derived mechanically.  No hand-written rearrangements, no per-relation
# boilerplate.
#
# Architecture:
#
#   public verbs   residual / check / solve      (β-or-T normalization, one place)
#   kernels        _residual (ONE per relation)  |  _solve (rare, non-affine only)
#   traits         variables / variable_slots / variable_types / quantities / domain
#   registry       all_relations / applicable_relations / relation_report / check_all
#   type-keyed     Bag / bag / VariableKey — residual/check/solve/report over a
#                  bag matched by quantity TYPE, not formula symbol (the front door)

"""
    AbstractRelation

Abstract parent type for physics relations.  Concrete relations are
declared with [`@relation`](@ref) and implement the three verbs:

- [`residual`](@ref)`(rel; vars...)` — signed violation; `0` ⇔ satisfied.
- [`check`](@ref)`(rel; atol=0, vars...)` — `|residual| ≤ atol`.
- [`solve`](@ref)`(rel, Val(:x); vars...)` — the value of `x` implied by
  the remaining variables.

The three verbs also have a **type-keyed** form — `residual(rel, b::Bag)`,
`check(rel, b)`, `solve(rel, Q::Type, b)` — that reads variables from a
[`bag`](@ref) by their quantity/field TYPE instead of a formula symbol; see
[`Bag`](@ref).

**Exact-arithmetic contract**: `residual` and `solve` must not promote
their inputs — `Rational` in ⇒ `Rational` out, so exactly-known values
(e.g. the 2D Ising exponents) satisfy their relations *exactly*
(`residual == 0//1`), not merely to floating-point tolerance.

Relations whose variables include an inverse temperature accept either
`β` or `T` (exactly one) at every public verb; the normalization happens
once, in the verb layer — kernels only ever see `β`.
"""
abstract type AbstractRelation end
export AbstractRelation

# the residual kernel generic function — one method per relation,
# generated by @relation.  Public code calls `residual`, never this.
function _residual end

# ─── Traits ─────────────────────────────────────────────────────────────

"""
    variables(rel::AbstractRelation) -> Tuple{Vararg{Symbol}}

The *required* variables of the relation (optional variables with
defaults, e.g. a site count `N = 1`, are not listed).  Filled in by
[`@relation`](@ref); used for applicability matching in
[`applicable_relations`](@ref) and by the β-or-T normalizer.
"""
function variables end
export variables

"""
    domain(rel::AbstractRelation) -> Symbol

The relation's family tag (`:scaling`, `:thermodynamic`,
`:fundamental`, `:topology`, …) — for filtering in the registry API,
and for disambiguating same-named variables across families (the
exponent `β` vs the inverse temperature `β`).
"""
function domain end
export domain

"""
    quantities(rel::AbstractRelation) -> Tuple{Vararg{Type}}

The physical-quantity TYPES a relation directly constrains — the machine
link from a relation to the vocabulary it speaks about (beyond the bare
variable *symbols* of [`variables`](@ref)).  E.g.
`quantities(SusceptibilityFDT()) == (Susceptibility,)`.  Defaults to `()`
for relations that constrain parameters/exponents rather than named
quantities (scaling laws, Maxwell relations).  The reverse index is
[`relations_constraining`](@ref).
"""
quantities(::AbstractRelation) = ()
export quantities

"""
    variable_slots(rel::AbstractRelation) -> Tuple{Vararg{Tuple{Symbol,Any}}}

For each *required* variable, its `(private-symbol, key)` pair, in declaration
order.  `key` is the variable's identity TYPE for an identity-bearing variable
(a quantity / field / coordinate / exponent, written `name::Type` in the
[`@relation`](@ref)) or `nothing` for a *supplied slot* (an untyped value — an
evaluation coordinate, a supplied integral; design note R3).  The private symbol
is the formula letter used in the residual body; the key is what the type-keyed
front door matches on.  Filled in by [`@relation`](@ref); `()`-ish for legacy
symbol-only relations (every slot `nothing`).
"""
variable_slots(::AbstractRelation) = ()
export variable_slots

"""
    variable_types(rel::AbstractRelation) -> Tuple{Vararg{Type}}

The identity TYPES of a relation's identity-bearing variables, in declaration
order (the non-`nothing` keys of [`variable_slots`](@ref)).  Empty for a legacy
symbol-only relation.  `quantities(rel)` is the `AbstractQuantity` subset of
this, auto-derived — so a type-keyed relation never needs a hand-written entry
in `quantity_links.jl`.
"""
variable_types(::AbstractRelation) = ()
export variable_types

# The AbstractQuantity subset of a variable-type tuple, family-erased via
# `_family` (`Susceptibility{I}` → `Susceptibility`; core/relation_variables.jl)
# and de-duplicated — a relation with two components of one family (HallAngle's
# `σxy`, `σxx`) constrains that family once — for the auto-derived `quantities`.
function _auto_quantities(types::Tuple)
    return Tuple(unique(_family(T) for T in types if T <: AbstractQuantity))
end

# ─── Registry ───────────────────────────────────────────────────────────

const _RELATION_REGISTRY = AbstractRelation[]

"""
    all_relations(; domain=nothing) -> Vector{AbstractRelation}

Every relation declared with [`@relation`](@ref) in this package,
optionally filtered by [`domain`](@ref).  The registry is what makes the
package *adoptable in one call*: a consumer never hand-lists relations
(see [`relation_report`](@ref)).
"""
function all_relations(; domain::Union{Nothing,Symbol}=nothing)
    domain === nothing && return copy(_RELATION_REGISTRY)
    return filter(r -> AbstractQAtlas.domain(r) === domain, _RELATION_REGISTRY)
end
export all_relations

"""
    relations_constraining(q) -> Vector{AbstractRelation}

Every registered relation that directly constrains the quantity `q` (its
type appears in the relation's [`quantities`](@ref)) — the reverse of
`quantities`, so a consumer can ask a quantity "which universal laws must
you obey?".  Accepts a quantity instance or its type.

```julia
relations_constraining(Susceptibility(:z, :z))   # [SusceptibilityFDT(), SusceptibilityResponse()]
```
"""
relations_constraining(q::AbstractQuantity) = relations_constraining(typeof(q))
function relations_constraining(::Type{Q}) where {Q<:AbstractQuantity}
    return filter(r -> any(T -> Q <: T, quantities(r)), _RELATION_REGISTRY)
end
export relations_constraining

# ─── β-or-T normalization (single point) ────────────────────────────────

# `solving` is the solve-target variable (or `nothing` for residual/
# check): when β itself is being solved for, the β-or-T demand is waived
# — the probes supply it.  (Physics overloads β: the same normalization
# serves the inverse temperature and steps aside for the exponent.)
function _normalize_kwargs(
    rel::AbstractRelation, kwargs::NamedTuple; solving::Union{Nothing,Symbol}=nothing
)
    :β in variables(rel) || return kwargs
    hasβ = haskey(kwargs, :β)
    hasT = haskey(kwargs, :T)
    if solving === :β
        (hasβ || hasT) && error("cannot pass β or T while solving for :β")
        return kwargs
    end
    hasβ && hasT && error("pass either β or T, not both")
    hasβ && return kwargs
    hasT || error("pass either β or T")
    rest = Base.structdiff(kwargs, NamedTuple{(:T,)})
    return merge(rest, (β=1 / kwargs.T,))
end

# ─── Public verbs ───────────────────────────────────────────────────────

"""
    residual(rel::AbstractRelation; vars...) -> Number

Signed violation of the relation at the given variable values; zero if
and only if the relation is satisfied.  Preserves the input number types
(see the exact-arithmetic contract on [`AbstractRelation`](@ref)).
"""
function residual(rel::AbstractRelation; kwargs...)
    return _residual(rel; _normalize_kwargs(rel, values(kwargs))...)
end
export residual

"""
    check(rel::AbstractRelation; atol=0, vars...) -> Bool

`abs(residual(rel; vars...)) ≤ atol`.  With the default `atol = 0` this
is an *exact* test — appropriate for `Rational` inputs; pass an explicit
`atol` for floating-point / error-bar data.
"""
check(rel::AbstractRelation; atol=0, kwargs...) = abs(residual(rel; kwargs...)) <= atol
export check

"""
    AbstractInequality <: AbstractRelation

A relation asserting an **inequality** rather than an equality.  Its
[`residual`](@ref) is the **slack in the `≥ 0` form**: the relation holds
iff `residual ≥ 0` (within tolerance), so [`check`](@ref) tests that
direction instead of `abs(residual) ≤ atol`.  [`solve`](@ref) still
returns the **saturation** value — where the slack vanishes, i.e. the
tight bound (e.g. `solve(Subadditivity(), Val(:S_AB))` gives the maximum
`S_A + S_B`).  Declared with [`@inequality`](@ref).
"""
abstract type AbstractInequality <: AbstractRelation end
export AbstractInequality

# an inequality holds when its slack is non-negative (float noise: ≥ −atol)
check(rel::AbstractInequality; atol=0, kwargs...) = residual(rel; kwargs...) >= -atol

"""
    slack(ineq::AbstractInequality; vars...) -> Number

The non-negativity margin of an inequality — its [`residual`](@ref): how
far from saturation, negative iff the inequality is violated.
"""
slack(rel::AbstractInequality; kwargs...) = residual(rel; kwargs...)
export slack

# whether a relation passes on the given (already-normalized) data — the
# polymorphic per-kind test used by `relation_report`/`check_all`, so an
# `AbstractInequality` is judged by its `≥ 0` direction, not `abs ≤ atol`.
_passes(rel::AbstractRelation, r, atol) = abs(r) <= atol
_passes(rel::AbstractInequality, r, atol) = r >= -atol

"""
    solve(rel::AbstractRelation, ::Val{x}; vars...) -> Number

The value of variable `x` implied by the relation and the remaining
variables, e.g. `solve(Widom(), Val(:γ); β=1//8, δ=15//1) == 7//4`.

No per-variable rearrangements are hand-written: for any variable the
relation is *affine* in (true of almost every identity here), the answer
follows exactly from three kernel evaluations — see the generic
`_solve`.  A relation that is non-affine in some variable provides a
specialized `_solve` for it (e.g. `FreeEnergyFromZ` for `Z`); attempting
a generic solve for a non-affine variable throws instead of silently
returning a wrong value.  Preserves input number types.
"""
function solve(rel::AbstractRelation, v::Val{X}; kwargs...) where {X}
    return _solve(rel, v; _normalize_kwargs(rel, values(kwargs); solving=X)...)
end
export solve

# Generic solve: for a residual r(x) affine in x, r(x) = r₀ + (r₁ − r₀)x
# exactly, so the root is x* = −r₀/(r₁ − r₀).  Three probes (x = 0, 1, 2)
# both solve and VERIFY affinity: the parabola test r₂ − 2r₁ + r₀ must
# vanish — exactly for exact inputs (Integer/Rational), to a relative
# 1e-8 for inexact ones (float OR complex-float — `abs` handles both).
# Integer probes promote correctly, so Rational data stays Rational.
function _solve(rel::AbstractRelation, ::Val{X}; kwargs...) where {X}
    kw = values(kwargs)
    at(v) = _residual(rel; merge(kw, NamedTuple{(X,)}((v,)))...)
    r0, r1, r2 = at(0), at(1), at(2)
    curv = r2 - 2r1 + r0
    isaffine = if curv isa Union{Integer,Rational}
        iszero(curv)                              # exact types: exact test
    elseif !all(isfinite, (r0, r1, r2))
        # A non-finite probe (a 1/x term evaluated at an integer probe, x=0)
        # means the residual blows up — not safely affine-solvable here.
        # Guard before `scale` goes to Inf and silently defeats the test.
        false
    else
        scale = max(abs(r0), abs(r1), abs(r2))    # float / complex: relative tol
        abs(curv) <= 1e-8 * max(scale, oneunit(scale))
    end
    isaffine || error(
        "solve: $(typeof(rel)) is not affine in :$X (or blows up at an integer " *
        "probe) — define a specialized _solve(::$(typeof(rel)), ::Val{:$X}; ...) " *
        "for this variable",
    )
    b = r1 - r0
    iszero(b) && error("solve: $(typeof(rel)) does not depend on :$X")
    return -r0 / b
end

# ─── The declaration macros ─────────────────────────────────────────────

# Shared code generation for `@relation` (equality) and `@inequality`
# (≥ 0 slack).  `super` is the supertype the generated struct subtypes,
# `what` names the macro for error messages.
function _build_relation(dom, defn, super::Symbol, what::String)
    Meta.isexpr(defn, :(=), 2) || error("$what expects `Name(vars...) = expr`, got $defn")
    call, body = defn.args
    Meta.isexpr(call, :call) || error("$what: left side must be a call, got $call")
    name = call.args[1]
    name isa Symbol || error("$what: relation name must be a Symbol")
    required = Symbol[]
    slotkeys = Any[]        # per required var: a Type expr (identity) or `nothing` (supplied slot)
    kwargsig = Any[]
    for p in call.args[2:end]
        if p isa Symbol
            # required, untyped SUPPLIED slot (an evaluation coordinate, a supplied integral)
            push!(required, p)
            push!(slotkeys, nothing)
            push!(kwargsig, esc(p))
        elseif Meta.isexpr(p, :(::), 2)
            # required, IDENTITY-bearing slot:  name::Type.  The type is bag-key
            # METADATA, not a value constraint — the kernel kwarg is untyped, so
            # a matrix-valued propagator still flows through unchanged.
            nm, ty = p.args[1], p.args[2]
            nm isa Symbol || error("$what: variable name must be a Symbol, got $nm")
            push!(required, nm)
            push!(slotkeys, ty)
            push!(kwargsig, esc(nm))
        elseif Meta.isexpr(p, :(=), 2) || Meta.isexpr(p, :kw, 2)
            lhs, dflt = p.args[1], p.args[2]
            nm = if lhs isa Symbol
                lhs
            elseif Meta.isexpr(lhs, :(::), 2)
                lhs.args[1]
            else
                nothing
            end
            nm isa Symbol || error("$what: cannot parse optional parameter $p")
            # keep `lhs` (WITH any `::Type`), not just the bare name — an optional
            # `N::Int = 1` must stay type-constrained in the generated kernel.
            push!(kwargsig, Expr(:kw, esc(lhs), esc(dflt)))
        else
            error("$what: cannot parse parameter $p")
        end
    end
    # kernels slurp extra keywords so relation_report can splat full data
    push!(kwargsig, Expr(:..., esc(gensym("extra"))))
    ename = esc(name)
    # NB: every generated method is module-QUALIFIED — short-form
    # definitions inside a macro quote are otherwise hygienized into
    # gensym locals, and qualification also makes the macros usable from
    # downstream modules (methods land on OUR generics, on THEIR type —
    # the intended extension pattern, not piracy).
    kernel_sig = Expr(
        :call, :(AbstractQAtlas._residual), Expr(:parameters, kwargsig...), :(::$ename)
    )
    kernel = Expr(:function, kernel_sig, esc(body))
    reqtuple = Expr(:tuple, (QuoteNode(s) for s in required)...)
    # variable_slots = ((:sym, KeyType | nothing), …); variable_types = the typed keys
    slotpairs = [
        Expr(:tuple, QuoteNode(s), k === nothing ? :nothing : esc(k)) for
        (s, k) in zip(required, slotkeys)
    ]
    slots_tuple = Expr(:tuple, slotpairs...)
    types_tuple = Expr(:tuple, (esc(k) for k in slotkeys if k !== nothing)...)
    has_typed = any(k -> k !== nothing, slotkeys)
    # a type-keyed relation auto-derives `quantities` from its typed slots — so it
    # needs no hand entry in quantity_links.jl; a legacy symbol-only relation keeps
    # the default / its quantity_links override.
    quantities_method = if has_typed
        :(
            AbstractQAtlas.quantities(r::$ename) =
                AbstractQAtlas._auto_quantities(AbstractQAtlas.variable_types(r))
        )
    else
        nothing
    end
    domval = QuoteNode(dom isa QuoteNode ? dom.value : dom)
    supertype = :(AbstractQAtlas.$super)
    return quote
        Core.@__doc__ struct $ename <: $supertype end
        $kernel
        AbstractQAtlas.variables(::$ename) = $reqtuple
        AbstractQAtlas.variable_slots(::$ename) = $slots_tuple
        AbstractQAtlas.variable_types(::$ename) = $types_tuple
        AbstractQAtlas.domain(::$ename) = $domval
        $quantities_method
        AbstractQAtlas._validate_relation($ename())   # load-time: concrete + distinct slots
        push!(AbstractQAtlas._RELATION_REGISTRY, $ename())
        $(Expr(:export, name))
        $ename
    end
end

# Load-time validation of a type-keyed relation's identity slots (runs when the
# `@relation` line is evaluated, so a mistake is loud at package load, never a
# silent degradation at use):
#   * every identity type must be CONCRETE — a bare parametric family (e.g.
#     `Susceptibility`) can never `===`-match a concrete bag key, so it would be a
#     permanently-dead relation (issue C4; real family-aware matching is a future
#     `support`-layer decision);
#   * the identity types must be DISTINCT — two slots of one type bind the SAME bag
#     value, giving an always-passing, physically meaningless check (issue C3; the
#     `support`/region layer is the escape valve for multi-instance-of-one-type).
function _validate_relation(rel::AbstractRelation)
    ts = variable_types(rel)
    isempty(ts) && return nothing
    nm = nameof(typeof(rel))
    for T in ts
        isconcretetype(T) || error(
            "@relation $nm: identity variable type `$T` is not concrete — a parametric " *
            "family cannot match a concrete bag key. Declare the concrete type, or wait " *
            "for the support / family-matching layer.",
        )
    end
    allunique(ts) || error(
        "@relation $nm: repeats an identity variable type in $ts — two slots of one type " *
        "share a bag key and the check would always pass. Distinguish them via `support` " *
        "(the region/point layer) or use different types.",
    )
    return nothing
end

"""
    @relation :domain Name(x, y, z, opt=default) = expr

Declare a relation ONCE.  Expands to the complete implementation:

- `struct Name <: AbstractRelation end` (docstring-attachable),
- the residual kernel `_residual(::Name; x, y, z, opt=default) = expr`
  (kernels tolerate extra keywords, so a whole data set can be splatted
  through [`relation_report`](@ref)),
- `variables(::Name) = (:x, :y, :z)` — required variables only,
- `domain(::Name) = :domain`,
- registry insertion and `export Name`.

`residual`/`check` work immediately; `solve` works for every variable
the expression is affine in.  Note for downstream packages declaring
their own relations: the struct and methods precompile fine, but the
registry insertion is a load-time side effect — re-register from your
module `__init__` if you need registry visibility across sessions.

```julia
@relation :scaling Rushbrooke(α, β, γ) = α + 2β + γ - 2
```
"""
macro relation(dom, defn)
    return _build_relation(dom, defn, :AbstractRelation, "@relation")
end
export var"@relation"

"""
    @inequality :domain Name(x, y, z, opt=default) = expr

Declare an INEQUALITY relation, `expr ≥ 0`.  Identical to
[`@relation`](@ref) but the generated struct subtypes
[`AbstractInequality`](@ref): `residual` returns the slack `expr`,
`check` tests `expr ≥ −atol`, and `solve` returns the saturation value.

```julia
@inequality :entanglement Subadditivity(S_A, S_B, S_AB) = S_A + S_B - S_AB
```
"""
macro inequality(dom, defn)
    return _build_relation(dom, defn, :AbstractInequality, "@inequality")
end
export var"@inequality"

# ─── Adoption surface: one-call verification over a data set ────────────

function _normalize_data(data::NamedTuple)
    return haskey(data, :T) && !haskey(data, :β) ? merge(data, (β=1 / data.T,)) : data
end

"""
    applicable_relations(data::NamedTuple; domain=nothing) -> Vector{AbstractRelation}

The registered relations whose required [`variables`](@ref) are all
present in `data` (after β-or-T normalization), optionally filtered by
[`domain`](@ref).  This is how a consumer package discovers what can be
checked against its observables — no hand-listing.

Pass `domain` when mixing families in one data set: variable names are
matched literally, and physics overloads symbols across families (the
critical exponent `β` vs the inverse temperature `β`).
"""
function applicable_relations(data::NamedTuple; domain::Union{Nothing,Symbol}=nothing)
    d = _normalize_data(data)
    ks = keys(d)
    return filter(r -> all(v -> v in ks, variables(r)), all_relations(; domain=domain))
end
export applicable_relations

"""
    relation_report(data::NamedTuple; atol=0, domain=nothing)
        -> Vector{@NamedTuple{relation::AbstractRelation, residual::Number, pass::Bool}}

Evaluate every applicable relation against `data` and report per-relation
residuals.  The one-call integration point for downstream packages:

```julia
# gate an exponent table (an atlas registry, MC-extracted exponents, …):
relation_report((; α=0//1, β=1//8, γ=7//4, δ=15//1, ν=1//1, η=1//4, d=2))

# cross-check measured thermodynamics against every applicable identity:
relation_report((; C=c, var_E=v, β=β, N=N); atol=tol)
```
"""
function relation_report(data::NamedTuple; atol=0, domain::Union{Nothing,Symbol}=nothing)
    d = _normalize_data(data)
    out = @NamedTuple{relation::AbstractRelation, residual::Number, pass::Bool}[]
    for rel in applicable_relations(d; domain=domain)
        r = _residual(rel; d...)
        push!(out, (relation=rel, residual=r, pass=_passes(rel, r, atol)))
    end
    return out
end
export relation_report

"""
    check_all(data::NamedTuple; atol=0, domain=nothing) -> Bool

`true` iff every applicable relation passes on `data` — and at least one
relation applies: an empty match is `false`, never a silent green.
"""
# the shared "all applicable relations passed, and at least one applied" rule — one
# place, so the NamedTuple and Bag `check_all` methods can't drift on "empty ⇒ false".
_all_passed(report) = !isempty(report) && all(row -> row.pass, report)

function check_all(data::NamedTuple; atol=0, domain::Union{Nothing,Symbol}=nothing)
    return _all_passed(relation_report(data; atol=atol, domain=domain))
end
export check_all

# ─── Type-keyed front door: the bag ─────────────────────────────────────
#
# The collision-proof surface (docs/design/type-keyed-interface.md): variables
# are read from a `bag` by their quantity / field TYPE, never by a formula-letter
# symbol, so the `:S`-means-four-things and `:G`-vs-`:GR` failures are
# structurally impossible.  Undecorated (`Global`) support only for now.  The
# residual math kernels are UNTOUCHED — this layer only translates
# `(type, support) → value` into the private-symbol kwargs the kernel already
# expects, so the exact-arithmetic contract carries over verbatim.
#
# Scope of "collision-proof": type keys prevent KEY collisions (two quantities
# sharing a slot).  A wrong VALUE stored under the RIGHT key is a separate class,
# caught by the numeric residual, not by the type system — the kernel keyword is
# deliberately untyped so matrix-valued inputs flow through.

"""
    Bag

A type-keyed data bag: `Dict{VariableKey,Any}` mapping a variable's
[`VariableKey`](@ref) to its value.  Build one with [`bag`](@ref).
"""
const Bag = Dict{VariableKey,Any}
export Bag

_as_key(k::VariableKey) = k
_as_key(@nospecialize(k::Type)) = VariableKey(k)
# a quantity / field / coordinate INSTANCE (e.g. `Susceptibility(:z, :z)`, the
# documented natural spelling) keys under its own type.
_as_key(v::RelationVariable) = VariableKey(typeof(v))

"""
    bag(pairs...) -> Bag

Build a type-keyed [`Bag`](@ref):
`bag(SpectralFunction => a, RetardedGreensFunction => g)`.  A `Type` key (or a
quantity/field INSTANCE, e.g. `Susceptibility(:z, :z)`) becomes
`VariableKey(Type)` (global support); a `VariableKey` key is used as-is.  The bag
is matched by TYPE, never by a string — two distinct quantities can never share a
key.  A `nothing` value is rejected: a bag holds concrete measured values, and an
absent variable must be *omitted*, not stored as `nothing` (which would be
indistinguishable from absent).

```julia
b = bag(KeldyshGreensFunction => gk, GreaterGreensFunction => gg, LesserGreensFunction => gl)
residual(KeldyshComponent(), b)      # G^K − (G^> + G^<)
```
"""
function bag(pairs::Pair...)
    b = Bag()
    for (k, v) in pairs
        v === nothing && error(
            "bag: the value for $(_as_key(k)) is `nothing` — a bag holds concrete " *
            "values; omit an absent variable rather than storing `nothing`.",
        )
        b[_as_key(k)] = v
    end
    return b
end
export bag

# Look up one identity slot in a bag, PRESENCE-aware: `Some(value)` if the key is
# present (even when the stored value is itself `nothing`), else `nothing` — so a
# truly absent key is never confused with a present-but-`nothing` one (issue C2).
# Honors the typed β-or-T conversion (InverseTemperature ⇄ Temperature) and,
# mirroring the symbol path's `_normalize_kwargs`, ERRORS if BOTH are supplied
# (issue C1: silently preferring one over a contradictory other is the hazard the
# type-keyed layer exists to remove).
function _slot_value(@nospecialize(ty::Type), b::Bag)
    if ty === InverseTemperature || ty === Temperature
        haskey(b, VariableKey(InverseTemperature)) &&
            haskey(b, VariableKey(Temperature)) &&
            error("bag has both InverseTemperature and Temperature — pass exactly one")
    end
    haskey(b, VariableKey(ty)) && return Some(b[VariableKey(ty)])
    if ty === InverseTemperature
        haskey(b, VariableKey(Temperature)) && return Some(1 / b[VariableKey(Temperature)])
    elseif ty === Temperature
        haskey(b, VariableKey(InverseTemperature)) &&
            return Some(1 / b[VariableKey(InverseTemperature)])
    end
    return nothing
end

# One slot's value, PRESENCE-aware (`Some`/`nothing`): identity slots from the bag
# `b` by type (β-or-T aware), supplied slots from `extras` by symbol.  Shared by
# the applicability check and the kwargs builder so the two can't drift.
function _resolve_slot(sym::Symbol, @nospecialize(key), b::Bag, extras)
    key === nothing || return _slot_value(key, b)
    return haskey(extras, sym) ? Some(extras[sym]) : nothing
end

# The private symbol `rel` keys under the identity type `ty` (`nothing` if none).
function _symbol_for(rel::AbstractRelation, @nospecialize(ty::Type))
    for (sym, key) in variable_slots(rel)
        key === ty && return sym
    end
    return nothing
end

# Every required variable available? — identity slots from `b` by type, supplied
# slots from `extras` by symbol.  A legacy symbol-only relation is never a match.
function _bag_applicable(rel::AbstractRelation, b::Bag, extras)
    isempty(variable_types(rel)) && return false
    return all(variable_slots(rel)) do (sym, key)
        return _resolve_slot(sym, key, b, extras) !== nothing
    end
end

# Build the private-symbol kwargs the kernel expects from `b` (identity slots) +
# `extras` (supplied slots); `skip` leaves one variable out (for `solve`).  Missing
# required values throw with a message naming the FULL type (so two components of
# one parametric family are never confused — issue I4).
function _bag_kwargs(
    rel::AbstractRelation, b::Bag, extras; skip::Union{Symbol,Nothing}=nothing
)
    out = Pair{Symbol,Any}[]
    for (sym, key) in variable_slots(rel)
        sym === skip && continue
        v = _resolve_slot(sym, key, b, extras)
        if v === nothing
            if key === nothing
                error(
                    "$(nameof(typeof(rel))) needs the supplied value :$sym (untyped slot)"
                )
            else
                error("$(nameof(typeof(rel))) needs $(key) in the bag")
            end
        end
        push!(out, sym => something(v))
    end
    return out
end

"""
    residual(rel::AbstractRelation, b::Bag; extras...) -> Number

Type-keyed [`residual`](@ref): read each identity-bearing variable from the bag
`b` by its quantity / field TYPE, each supplied (untyped) slot from `extras`, and
evaluate.  Same value and exact-arithmetic contract as the symbol-keyed method —
the collision-proof front door.

```julia
residual(SpectralFromGreens(), bag(SpectralFunction => A, RetardedGreensFunction => G))
```
"""
function residual(rel::AbstractRelation, b::Bag; extras...)
    return _residual(rel; _bag_kwargs(rel, b, values(extras))...)
end

"""
    check(rel::AbstractRelation, b::Bag; atol=0, extras...) -> Bool

Type-keyed [`check`](@ref): `residual(rel, b; extras...)` within `atol`
(equalities `|·| ≤ atol`, inequalities `· ≥ −atol`).
"""
function check(rel::AbstractRelation, b::Bag; atol=0, extras...)
    return _passes(rel, residual(rel, b; extras...), atol)
end

"""
    solve(rel::AbstractRelation, Q::Type, b::Bag; extras...) -> Number

Type-keyed [`solve`](@ref): the value of the variable whose identity type is `Q`,
implied by the relation and the others (read from `b` / `extras`).  Translates
`Q` to its private slot and defers to the affine symbol-keyed solver, so exact
arithmetic is preserved.

```julia
solve(KeldyshComponent(), KeldyshGreensFunction,
      bag(GreaterGreensFunction => 2, LesserGreensFunction => 3))    # 5
```
"""
function solve(rel::AbstractRelation, @nospecialize(Q::Type), b::Bag; extras...)
    sym = _symbol_for(rel, Q)
    sym === nothing && error("$(nameof(typeof(rel))) has no variable of type $(nameof(Q))")
    return solve(rel, Val(sym); _bag_kwargs(rel, b, values(extras); skip=sym)...)
end

"""
    applicable_relations(b::Bag; domain=nothing, extras...) -> Vector{AbstractRelation}

The type-keyed analogue of [`applicable_relations`](@ref): every registered
type-keyed relation whose identity variables' TYPES are all present in `b` (with
`Temperature ⇄ InverseTemperature` accepted) and whose supplied slots are all in
`extras`.  No string matching, hence no cross-quantity collision — `domain` is
only for scoping, never disambiguation.
"""
function applicable_relations(b::Bag; domain::Union{Nothing,Symbol}=nothing, extras...)
    ex = values(extras)
    return filter(r -> _bag_applicable(r, b, ex), all_relations(; domain=domain))
end

"""
    relation_report(b::Bag; atol=0, domain=nothing, extras...)

Type-keyed [`relation_report`](@ref): evaluate every applicable type-keyed
relation against the bag `b` (plus `extras` for supplied slots) and report
per-relation residuals.  The collision-proof verify-engine front door.
"""
function relation_report(b::Bag; atol=0, domain::Union{Nothing,Symbol}=nothing, extras...)
    ex = values(extras)
    out = @NamedTuple{relation::AbstractRelation, residual::Number, pass::Bool}[]
    for rel in applicable_relations(b; domain=domain, extras...)
        r = residual(rel, b; ex...)
        push!(out, (relation=rel, residual=r, pass=_passes(rel, r, atol)))
    end
    return out
end

"""
    check_all(b::Bag; atol=0, domain=nothing, extras...) -> Bool

`true` iff every applicable type-keyed relation passes on the bag `b` — and at
least one applies (an empty match is `false`).
"""
function check_all(b::Bag; atol=0, domain::Union{Nothing,Symbol}=nothing, extras...)
    return _all_passed(relation_report(b; atol=atol, domain=domain, extras...))
end
